FROM node:16-alpine

ARG NODE_ENV
RUN echo ${NODE_ENV}
WORKDIR /app

COPY package*.json ./
RUN if [[ ${NODE_ENV} = "production" ]]; then npm ci --only=production; else npm install; fi

ENV NPM_CONFIG_LOGLEVEL warn
ENV NODE_ENV ${NODE_ENV}

EXPOSE 3000

CMD ["node", "./src/bin/www"]
